[package]
name = "typhoon"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.18.1" }
starknet = "2.11.4"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
snforge_std = "0.34.0"
# cairo_test = "2.11.4"

assert_macros = "2.9.1"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[scripts]
test = "snforge test"
